### ISSUE TITLE
Make language selector

### ISSUE THREAD

**Issue by bafplus** [jaullo/Snappy#6]
The used language is now hardcoded in source.
Would be nice to have a language selector in the settingsscreen so users can select a prefered language and save as user-setting.

**Comment by jaullo** [comment]
Hello @bafplus, 
I'm working on this right now. There is no difficult to implement. 

Best regards

**Comment by jaullo** [comment]
New languages was added so iy's not necessary a languaje selector. Just change your phone languaje
