### ISSUE TITLE
server-move strings to languagefile

### ISSUE THREAD

**Issue by bafplus** [jaullo/Snappy#7]
In config/init.php there are some language strings that are used in the sidebar notifications (you have a new message from... etc).
When you change the language these strings are not changed and are stil english.
Can these strings be moved to the languagefiles?

define("DIRECTMESSAGE_NOTIFICATION_MESSAGE", "You got message from %s");
define("GROUPMESSAGE_NOTIFICATION_MESSAGE", "%s posted message to group %s");
define("ACTIVITY_SUMMARY_DIRECT_MESSAGE", "direct_messages");
define("ACTIVITY_SUMMARY_GROUP_MESSAGE", "group_posts");

**Comment by jaullo** [comment]
Hello @bafplus,
You're right, i'm working on this too. I have this feature at a 80%

Best regards.

**Comment by jaullo** [comment]
Ready. This  was implemented. These strings are now translated

**Comment by bafplus** [comment]
Are you sure? Cant find these changes.....

**Comment by jaullo** [comment]
Yes, sure

**Comment by jaullo** [comment]
@bafplus check now the repo.
