### ISSUE TITLE
Problems getting server to send/recieve push

### ISSUE THREAD

**Issue by bafplus** [jaullo/Snappy#8]
Hy,

I have setup a ubuntu 14.10 server and manage to get the server running.
Only thing that doesent work are the push messages and teh autorefresh.

What i have done so far:

App:
- I used the master code from Spika
- Setup and build according to there instructions

The app works with the Spika Official Server and even the push works, so i know the code is correct.
- Put my Google Maps API-KEY in init.php 
- Put PUSH_SENDER_ID (app-id) in Const.java
  Rebuild the app.
  App can connect to Spika Official but push doesent work anymore (what is expected since i changed the APP-ID)

Server:
- Installed according to instructions on Spika website.
- Replaced PushNotificationProvider.php and changed the server api-key
- Changed server api key in init.php

I tried this with different api keys but still no push messages.
I am no developer so i cant find the bug in this.
Also i see no api response if i look at the quota screen for push messages.
The maps api works and there is activiti logged when ussing it.

Is there someone who can help me getting the push to work?

Beers available ;-)

**Comment by jaullo** [comment]
Hello @bafplus do u want to be an active developer for this project?
Any functionality is welcome.

For now i have a test server with push notifications working (push notification problem in spika is on server side not app side), i couldn't release it to the public because some times is unstable.

Send me a PM and we can talk

Best regards

**Comment by superahmad** [comment]
@jaullo can you help me? my email abufaizmtx@gmail.com

**Comment by jaullo** [comment]
Hello @superahmad i gonna send u an email tomorrow. I can help u with this issue.
I'm.only supporting the project on this sitie, so no updates will released on the original spika github site

Best regards

**Comment by jaullo** [comment]
Hello @superahmad 
Did you get the server to work?

**Comment by superahmad** [comment]
yes @jaullo

**Comment by jaullo** [comment]
I'm glad to hear that :)
